# stack4-central-mirror/cloud-init.yml
#cloud-config

package_update: true
package_upgrade: true

packages:
  - nginx
  - rsync
  - wget
  - curl
  - createrepo_c
  - yum-utils
  - subscription-manager
  - dnf-utils
  - httpd-tools

write_files:
  - path: /etc/nginx/sites-available/repo-mirror
    content: |
      server {
          listen 80;
          server_name _;
          root /var/www/repos;

          # Main repository index
          location / {
              autoindex on;
              autoindex_exact_size off;
              autoindex_localtime on;
              add_header Content-Type text/html;
          }

          # RHEL repositories - major versions
          location ~ ^/rhel/([89])/ {
              alias /var/www/repos/rhel/;
              autoindex on;
              try_files $uri $uri/ =404;
          }

          # RHEL repositories - minor versions (8.8, 9.3, etc.)
          location ~ ^/rhel/([89]\.[0-9]+)/ {
              alias /var/www/repos/rhel/;
              autoindex on;
              try_files $uri $uri/ =404;
          }

          # CentOS Stream repositories
          location ~ ^/centos/(8|9)-stream/ {
              alias /var/www/repos/centos/;
              autoindex on;
              try_files $uri $uri/ =404;
          }

          # Security headers
          add_header X-Content-Type-Options nosniff;
          add_header X-Frame-Options DENY;
          add_header X-XSS-Protection "1; mode=block";
      }

  - path: /usr/local/bin/setup-mirror.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e

      # Mount and format data disk
      if ! mountpoint -q /var/www/repos; then
          mkfs.xfs /dev/sdc
          mkdir -p /var/www/repos
          mount /dev/sdc /var/www/repos
          echo "/dev/sdc /var/www/repos xfs defaults 0 2" >> /etc/fstab
      fi

      # Set permissions
      chown -R nginx:nginx /var/www/repos
      chmod -R 755 /var/www/repos

      # Create RHEL repository structure
      mkdir -p /var/www/repos/{rhel,centos}

      # RHEL 8 structure
      mkdir -p /var/www/repos/rhel/8/{BaseOS,AppStream,CodeReady}
      mkdir -p /var/www/repos/rhel/8.{8,9,10}/{BaseOS,AppStream,CodeReady}

      # RHEL 9 structure
      mkdir -p /var/www/repos/rhel/9/{BaseOS,AppStream,CodeReady}
      mkdir -p /var/www/repos/rhel/9.{0,1,2,3,4}/{BaseOS,AppStream,CodeReady}

      # CentOS Stream structure
      mkdir -p /var/www/repos/centos/{8,9}-stream/{BaseOS,AppStream,extras,PowerTools}

      # Configure nginx (RHEL uses nginx package)
      systemctl enable nginx
      ln -sf /etc/nginx/sites-available/repo-mirror /etc/nginx/conf.d/repo-mirror.conf 2>/dev/null || {
          # For RHEL, create the config directly
          cp /etc/nginx/sites-available/repo-mirror /etc/nginx/conf.d/repo-mirror.conf
      }
      systemctl restart nginx

      # Install Azure CLI
      rpm --import https://packages.microsoft.com/keys/microsoft.asc
      dnf install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm
      dnf install -y azure-cli

      # Install azcopy
      cd /tmp
      wget https://aka.ms/downloadazcopy-v10-linux
      tar -xvf downloadazcopy-v10-linux
      cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/
      chmod +x /usr/local/bin/azcopy

      # Create sync script
      cat > /usr/local/bin/sync-to-blob.sh << 'EOF'
      #!/bin/bash
      echo "Starting blob sync at $(date)"

      # Authenticate using managed identity
      az login --identity

      # Sync repositories to blob storage
      azcopy sync /var/www/repos/ "https://${storage_account_name}.blob.core.windows.net/${container_name}/" \
        --recursive=true \
        --delete-destination=false \
        --exclude-pattern="*.tmp;*.lock;repodata/TRANS.TBL"

      echo "Repository sync completed at $(date)"
      EOF

      chmod +x /usr/local/bin/sync-to-blob.sh

      # Create RHEL repository sync script
      cat > /usr/local/bin/mirror-rhel.sh << 'EOF'
      #!/bin/bash
      echo "Starting RHEL repository mirror sync at $(date)"

      # Check if registered
      if ! subscription-manager status | grep -q "Overall Status: Current"; then
          if [ -n "$RHEL_USERNAME" ] && [ -n "$RHEL_PASSWORD" ]; then
              echo "Registering system with Red Hat..."
              subscription-manager register --username="$RHEL_USERNAME" --password="$RHEL_PASSWORD" --auto-attach
          else
              echo "RHEL credentials not provided. Cannot sync RHEL repositories."
              exit 1
          fi
      fi

      # Enable required repositories
      subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms \
                                --enable rhel-8-for-x86_64-appstream-rpms \
                                --enable codeready-builder-for-rhel-8-x86_64-rpms \
                                --enable rhel-9-for-x86_64-baseos-rpms \
                                --enable rhel-9-for-x86_64-appstream-rpms \
                                --enable codeready-builder-for-rhel-9-x86_64-rpms

      # Sync RHEL 8 repositories
      echo "Syncing RHEL 8 repositories..."
      for repo in rhel-8-for-x86_64-baseos-rpms rhel-8-for-x86_64-appstream-rpms codeready-builder-for-rhel-8-x86_64-rpms; do
          echo "Syncing $repo..."
          reposync --gpgcheck --newest-only --delete --downloadcomps \
                   --download-metadata --repoid=$repo \
                   --destdir=/var/www/repos/rhel/8/
      done

      # Sync RHEL 9 repositories
      echo "Syncing RHEL 9 repositories..."
      for repo in rhel-9-for-x86_64-baseos-rpms rhel-9-for-x86_64-appstream-rpms codeready-builder-for-rhel-9-x86_64-rpms; do
          echo "Syncing $repo..."
          reposync --gpgcheck --newest-only --delete --downloadcomps \
                   --download-metadata --repoid=$repo \
                   --destdir=/var/www/repos/rhel/9/
      done

      # Create repository metadata
      for version in 8 9; do
          for repo_type in BaseOS AppStream CodeReady; do
              repo_path="/var/www/repos/rhel/$version/$repo_type"
              if [ -d "$repo_path" ] && [ -n "$(find "$repo_path" -name "*.rpm" -type f)" ]; then
                  echo "Creating metadata for $repo_path"
                  createrepo_c --update "$repo_path"
              fi
          done
      done

      # Create repository index
      cat > /var/www/repos/index.html << 'HTML'
      <!DOCTYPE html>
      <html>
      <head><title>Red Hat Repository Mirror</title></head>
      <body>
      <h1>Red Hat Enterprise Linux Repository Mirror</h1>
      <ul>
        <li><a href="rhel/">RHEL Repositories</a>
          <ul>
            <li><a href="rhel/8/">RHEL 8</a></li>
            <li><a href="rhel/9/">RHEL 9</a></li>
          </ul>
        </li>
        <li><a href="centos/">CentOS Stream Repositories</a>
          <ul>
            <li><a href="centos/8-stream/">CentOS Stream 8</a></li>
            <li><a href="centos/9-stream/">CentOS Stream 9</a></li>
          </ul>
        </li>
      </ul>
      <p>Last updated: $(date)</p>
      </body>
      </html>
      HTML

      echo "RHEL mirror sync completed at $(date)"
      EOF

      chmod +x /usr/local/bin/mirror-rhel.sh

      # Create CentOS Stream mirror script
      cat > /usr/local/bin/mirror-centos.sh << 'EOF'
      #!/bin/bash
      echo "Starting CentOS Stream repository mirror sync at $(date)"

      # Sync CentOS Stream 8
      echo "Syncing CentOS Stream 8..."
      rsync -avz --delete --exclude='debug/' \
        rsync://mirror.centos.org/centos/8-stream/ \
        /var/www/repos/centos/8-stream/

      # Sync CentOS Stream 9
      echo "Syncing CentOS Stream 9..."
      rsync -avz --delete --exclude='debug/' \
        rsync://mirror.centos.org/centos/9-stream/ \
        /var/www/repos/centos/9-stream/

      echo "CentOS Stream mirror sync completed at $(date)"
      EOF

      chmod +x /usr/local/bin/mirror-centos.sh

  - path: /etc/cron.d/repo-sync
    content: |
      # RHEL repository synchronization schedule
      0 2 * * * root RHEL_USERNAME="${redhat_username}" RHEL_PASSWORD="${redhat_password}" /usr/local/bin/mirror-rhel.sh >> /var/log/rhel-sync.log 2>&1
      30 3 * * * root /usr/local/bin/mirror-centos.sh >> /var/log/centos-sync.log 2>&1
      0 5 * * * root /usr/local/bin/sync-to-blob.sh >> /var/log/blob-sync.log 2>&1

  - path: /etc/yum.repos.d/local-mirror.repo
    content: |
      # Local RHEL mirror configuration template
      [rhel-8-baseos-local]
      name=Red Hat Enterprise Linux 8 - BaseOS (Local Mirror)
      baseurl=http://localhost/rhel/8/BaseOS
      enabled=0
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

      [rhel-8-appstream-local]
      name=Red Hat Enterprise Linux 8 - AppStream (Local Mirror)
      baseurl=http://localhost/rhel/8/AppStream
      enabled=0
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

      [rhel-9-baseos-local]
      name=Red Hat Enterprise Linux 9 - BaseOS (Local Mirror)
      baseurl=http://localhost/rhel/9/BaseOS
      enabled=0
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

      [rhel-9-appstream-local]
      name=Red Hat Enterprise Linux 9 - AppStream (Local Mirror)
      baseurl=http://localhost/rhel/9/AppStream
      enabled=0
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

runcmd:
  - /usr/local/bin/setup-mirror.sh
  - systemctl restart crond