# stack4-central-mirror/cloud-init.yml
#cloud-config

package_update: true
package_upgrade: true

packages:
  - nginx
  - apache2-utils
  - rsync
  - wget
  - curl
  - apt-mirror
  - apt-cacher-ng
  - debmirror

write_files:
  - path: /etc/nginx/sites-available/repo-mirror
    content: |
      server {
          listen 80;
          server_name _;
          root /var/www/repos;

          # Main repository index
          location / {
              autoindex on;
              autoindex_exact_size off;
              autoindex_localtime on;
              add_header Content-Type text/html;
          }

          # Ubuntu repositories
          location /ubuntu/ {
              alias /var/www/repos/ubuntu/;
              autoindex on;
              try_files $uri $uri/ =404;
          }

          # Security headers
          add_header X-Content-Type-Options nosniff;
          add_header X-Frame-Options DENY;
          add_header X-XSS-Protection "1; mode=block";
      }

  - path: /etc/apt/mirror.list
    content: |
      ############# config ##################
      set base_path    /var/www/repos
      set mirror_path  $base_path/ubuntu
      set skel_path    $base_path/skel
      set var_path     $base_path/var
      set cleanscript $var_path/clean.sh
      set defaultarch  amd64
      set postmirror_script $var_path/postmirror.sh
      set run_postmirror 0
      set nthreads     20
      set _tilde 0

      ############# Ubuntu LTS repos ############
      # Ubuntu 22.04 LTS (Jammy)
      deb-amd64 http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse

      # Ubuntu 20.04 LTS (Focal)
      deb-amd64 http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu focal-security main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse

      # Ubuntu 24.04 LTS (Noble)
      deb-amd64 http://archive.ubuntu.com/ubuntu noble main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu noble-security main restricted universe multiverse
      deb-amd64 http://archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse

      clean http://archive.ubuntu.com/ubuntu

  - path: /usr/local/bin/setup-mirror.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e

      # Mount and format data disk
      if ! mountpoint -q /var/www/repos; then
          mkfs.ext4 /dev/sdc
          mkdir -p /var/www/repos
          mount /dev/sdc /var/www/repos
          echo "/dev/sdc /var/www/repos ext4 defaults 0 2" >> /etc/fstab
      fi

      # Set permissions
      chown -R www-data:www-data /var/www/repos
      chmod -R 755 /var/www/repos

      # Create Ubuntu repository structure
      mkdir -p /var/www/repos/{ubuntu,skel,var}

      # Enable nginx site
      ln -sf /etc/nginx/sites-available/repo-mirror /etc/nginx/sites-enabled/
      rm -f /etc/nginx/sites-enabled/default
      systemctl restart nginx
      systemctl enable nginx

      # Install Azure CLI
      curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      # Install azcopy
      cd /tmp
      wget https://aka.ms/downloadazcopy-v10-linux
      tar -xvf downloadazcopy-v10-linux
      cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/
      chmod +x /usr/local/bin/azcopy

      # Create sync script
      cat > /usr/local/bin/sync-to-blob.sh << 'EOF'
      #!/bin/bash
      echo "Starting blob sync at $(date)"

      # Authenticate using managed identity
      az login --identity

      # Sync repositories to blob storage
      azcopy sync /var/www/repos/ "https://${storage_account_name}.blob.core.windows.net/${container_name}/" \
        --recursive=true \
        --delete-destination=false \
        --exclude-pattern="*.tmp;*.lock"

      echo "Repository sync completed at $(date)"
      EOF

      chmod +x /usr/local/bin/sync-to-blob.sh

      # Create Ubuntu mirror sync script
      cat > /usr/local/bin/mirror-ubuntu.sh << 'EOF'
      #!/bin/bash
      echo "Starting Ubuntu repository mirror sync at $(date)"

      # Run apt-mirror
      cd /var/www/repos
      apt-mirror /etc/apt/mirror.list

      # Create repository index
      cat > /var/www/repos/index.html << 'HTML'
      <!DOCTYPE html>
      <html>
      <head><title>Ubuntu Repository Mirror</title></head>
      <body>
      <h1>Ubuntu Repository Mirror</h1>
      <ul>
        <li><a href="ubuntu/">Ubuntu Repositories</a>
          <ul>
            <li><a href="ubuntu/archive.ubuntu.com/ubuntu/dists/noble/">Ubuntu 24.04 LTS (Noble)</a></li>
            <li><a href="ubuntu/archive.ubuntu.com/ubuntu/dists/jammy/">Ubuntu 22.04 LTS (Jammy)</a></li>
            <li><a href="ubuntu/archive.ubuntu.com/ubuntu/dists/focal/">Ubuntu 20.04 LTS (Focal)</a></li>
          </ul>
        </li>
      </ul>
      <p>Last updated: $(date)</p>
      </body>
      </html>
      HTML

      echo "Ubuntu mirror sync completed at $(date)"
      EOF

      chmod +x /usr/local/bin/mirror-ubuntu.sh

  - path: /etc/cron.d/repo-sync
    content: |
      # Ubuntu repository synchronization schedule
      0 2 * * * root /usr/local/bin/mirror-ubuntu.sh >> /var/log/ubuntu-sync.log 2>&1
      0 5 * * * root /usr/local/bin/sync-to-blob.sh >> /var/log/blob-sync.log 2>&1

runcmd:
  - /usr/local/bin/setup-mirror.sh
  - systemctl restart cron